# Generated by Django 4.2.5 on 2023-09-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformcode', models.TextField(blank=True, db_column='PlatformCode', null=True)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('npv', models.TextField(blank=True, db_column='NPV', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('shelf', models.TextField(blank=True, db_column='Shelf', null=True)),
            ],
        ),
    ]
